# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
      include: scope

  - package-ecosystem: npm
    directories:
      - /reference-architectures/app/api/typescript/openai-agents-sdk
      - /reference-architectures/app/api/typescript/foundry-agent-service
      - /reference-architectures/app/frontend/typescript/react
    schedule:
      interval: weekly
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: nuget
    directory: /reference-architectures/app/api/csharp/microsoft-agent-framework
    schedule:
      interval: weekly
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: devcontainers
    directory: /.devcontainer
    schedule:
      interval: weekly
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: terraform
    directories:
      - /reference-architectures/iac/foundry
      - /reference-architectures/iac/container-apps
    schedule:
      interval: weekly
    commit-message:
      prefix: build
      include: scope
