# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Check PR

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ format('{0}-{1}-{2}-{3}-{4}', github.workflow, github.event_name, github.ref, github.base_ref || null, github.head_ref || null) }}
  cancel-in-progress: true

env:
  PR_URL: ${{ github.event.pull_request.html_url }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  check-should-run:
    uses: ./.github/workflows/_allow_workflow_run.yml

  check_pr:
    needs: check-should-run
    name: Check PR
    runs-on: ubuntu-24.04
    if: needs.check-should-run.outputs.should_run == 'true'
    steps:
      - name: 🩺 Debug
        uses: raven-actions/debug@9dbdeb7eea607a7d73411895c65987e71d59a466 # v1.2.0

      - name: ⤵️ Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: 🚧 Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: lts/*

      - name: 🚧 Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: stable
          check-latest: true

      - name: 🚧 Setup Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          repo-token: ${{ github.token }}

      - name: 🔨 Setup tools
        run: |
          task internal:setup:uv
          task tools
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: 📃 Generate docs
        run: task docs

      - name: 🤖 Bot details
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        id: bot-details
        uses: raven-actions/bot-details@b2d5fd6eb98adc0cb67df864daa834849f3a8bc0 # v1.1.0
        with:
          bot-slug-name: dependabot

      - name: 📤 Dependabot auto-commit (docs)
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        with:
          commit_message: "docs: automatic updates"
          commit_user_name: ${{ steps.bot-details.outputs.name }}
          commit_user_email: ${{ steps.bot-details.outputs.email }}
          commit_options: "--no-verify --signoff"

      - name: 🔀 Check for differences
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "🛑 Unexpected difference. Run 'task docs' command and commit."; git diff --exit-code)

      - name: 🏗️ Build Site
        run: task site:build -- --strict

      - name: 📝 Fetch Dependabot metadata
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0
        with:
          alert-lookup: true
          compat-lookup: true

      - name: 🏷️ Label (security)
        if: github.event.pull_request.user.login == 'dependabot[bot]' && (steps.dependabot-metadata.outputs.ghsa-id != '' || steps.dependabot-metadata.outputs.cvss != 0)
        run: gh pr edit --add-label "area/security" "${PR_URL}"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: 🤝 Enable auto-merge
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: gh pr merge --auto --squash "${PR_URL}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
